name: weather_app
description: A weather forecast app with video backgrounds.

publish_to: 'none' # Remove this line if you're publishing the app

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  http: ^0.13.5
  json_annotation: ^4.8.1
  video_player: ^2.7.2
  csc_picker: # ðŸŒ Using a Git fork to fix a compatibility issue
    git:
      url: https://github.com/iamageo/csc_picker.git
      ref: master
  timezone: ^0.9.3 # â° Package for time zone management

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - lib/assets/thunderstorm.mp4
    - lib/assets/rainy.mp4
    - lib/assets/snowy.mp4
    - lib/assets/cloudy.mp4
    - lib/assets/sunny.mp4